baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'CraftCMS 4 Boilerplate'
primary: true
siteGroup: 59c0ba4b-eb41-4f12-8dc4-982a569daf61 # Craft Boilerplate
sortOrder: 1
