dateModified: 1676466428
email:
  fromEmail: jorgeanzola@gmail.com
  fromName: 'Craft Boilerplate'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3e035f01-35ee-4470-bb4a-284e1eedbb1e: Common # Common
    59c0ba4b-eb41-4f12-8dc4-982a569daf61: 'Craft Boilerplate' # Craft Boilerplate
    a6f959fd-37bc-42be-9fb8-78d8ce1ba9d5: 'CraftCMS 4 Boilerplate' # CraftCMS 4 Boilerplate
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Boilerplate'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
